CREATE TABLE INFORMATION_SCHEMA.TABLES
(
    TABLE_CATALOG nvarchar(128),
    TABLE_SCHEMA sysname,
    TABLE_NAME sysname NOT NULL,
    TABLE_TYPE varchar(10)
);
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Langues', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Preferences', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Producteurs', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Realisateurs', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'SousTitres', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Supplements', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'TypesUtilisateur', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Categories', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'FilmsActeurs', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Films', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'EmpruntsFilms', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'FilmsSousTitres', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'FilmsSupplements', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'FilmsLangues', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'UtilisateursPreferences', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Utilisateurs', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Exemplaires', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'ValeursPreferences', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'sysdiagrams', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Acteurs', 'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES ('BD5W6_424P', 'dbo', 'Formats', 'BASE TABLE');