CREATE TABLE sys.system_internals_partitions
(
    partition_id bigint NOT NULL,
    object_id int NOT NULL,
    index_id int NOT NULL,
    partition_number int NOT NULL,
    rows bigint NOT NULL,
    filestream_filegroup_id smallint NOT NULL,
    is_orphaned bit,
    dropped_lob_column_state tinyint,
    is_unique bit,
    is_replicated bit,
    is_logged_for_replication bit,
    max_null_bit_used smallint NOT NULL,
    max_leaf_length int NOT NULL,
    min_leaf_length smallint NOT NULL,
    max_internal_length smallint NOT NULL,
    min_internal_length smallint NOT NULL,
    allows_nullable_keys bit,
    allow_row_locks bit,
    allow_page_locks bit,
    is_data_row_format bit,
    is_not_versioned bit,
    filestream_guid uniqueidentifier
);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (196608, 3, 1, 1, 701, 0, 0, 2, 1, 0, 0, 14, 82, 58, 19, 19, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (327680, 5, 1, 1, 113, 0, 0, 0, 1, 0, 0, 18, 92, 57, 18, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (458752, 7, 1, 1, 127, 0, 0, 0, 1, 0, 0, 12, 77, 73, 18, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (524288, 8, 0, 1, 2, 0, 0, 0, 0, 0, 0, 4, 803, 786, 0, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474977824768, 17, 1, 1, 0, 0, 0, 2, 1, 0, 0, 6, 794, 17, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474977955840, 19, 1, 1, 2, 0, 0, 2, 1, 0, 0, 5, 27, 24, 23, 23, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474978217984, 23, 1, 1, 1, 0, 0, 2, 1, 0, 0, 8, 305, 42, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474978283520, 24, 1, 1, 2, 0, 0, 2, 1, 0, 0, 31, 1036, 248, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474978349056, 25, 1, 1, 0, 0, 0, 0, 1, 0, 0, 15, 83, 79, 15, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474978480128, 27, 1, 1, 15, 0, 0, 0, 1, 0, 0, 9, 908, 29, 15, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474978611200, 29, 1, 1, 145, 0, 0, 0, 1, 0, 0, 7, 29, 26, 31, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474978938880, 34, 1, 1, 124, 0, 0, 0, 1, 0, 0, 11, 320, 44, 15, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474979397632, 41, 1, 1, 567, 0, 0, 0, 1, 0, 0, 16, 387, 45, 20, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474979594240, 44, 1, 1, 1, 0, 0, 0, 1, 0, 0, 8, 312, 37, 15, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474979725312, 46, 1, 1, 0, 0, 0, 2, 1, 0, 0, 10, 11228, 22, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474979921920, 49, 1, 1, 9, 0, 0, 2, 1, 0, 0, 5, 8294, 13, 276, 16, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474979987456, 50, 1, 1, 34, 0, 0, 0, 1, 0, 0, 13, 325, 49, 15, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980052992, 51, 1, 1, 0, 0, 0, 0, 1, 0, 0, 12, 310, 34, 19, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980249600, 54, 1, 1, 285, 0, 0, 0, 1, 0, 0, 11, 315, 39, 18, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980315136, 55, 1, 1, 445, 0, 0, 0, 1, 0, 0, 7, 29, 26, 22, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980511744, 58, 1, 1, 23, 0, 0, 2, 1, 0, 0, 9, 303, 39, 15, 12, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980577280, 59, 1, 1, 0, 0, 0, 2, 1, 0, 0, 7, 29, 26, 28, 28, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980642816, 60, 1, 1, 295, 0, 0, 2, 1, 0, 0, 6, 73589, 17, 23, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980904960, 64, 1, 1, 16, 0, 0, 0, 1, 0, 0, 8, 310, 35, 15, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474980970496, 65, 1, 1, 0, 0, 0, 0, 1, 0, 0, 6, 32, 29, 23, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981101568, 67, 1, 1, 0, 0, 0, 2, 1, 0, 0, 5, 793, 16, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981167104, 68, 1, 1, 0, 0, 0, 2, 1, 0, 0, 20, 10663, 82, 32, 32, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981232640, 69, 1, 1, 1, 0, 0, 2, 1, 0, 0, 7, 2079, 16, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981363712, 71, 1, 1, 0, 0, 0, 2, 1, 0, 0, 4, 35, 32, 23, 23, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981429248, 72, 1, 1, 0, 0, 0, 2, 1, 0, 0, 5, 54, 51, 23, 23, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981494784, 73, 1, 1, 0, 0, 0, 2, 1, 0, 0, 27, 1076, 180, 24, 24, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981560320, 74, 1, 1, 215, 0, 0, 0, 1, 0, 0, 6, 28, 25, 19, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981625856, 75, 1, 1, 132, 0, 0, 0, 1, 0, 0, 6, 28, 25, 27, 0, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474981822464, 78, 1, 1, 0, 0, 0, 2, 1, 0, 0, 5, 36, 33, 16, 16, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982084608, 82, 1, 1, 0, 0, 0, 2, 1, 0, 0, 8, 55, 52, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982281216, 85, 1, 1, 0, 0, 0, 2, 1, 0, 0, 4, 148, 13, 147, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982608896, 90, 1, 1, 97, 0, 0, 2, 1, 0, 0, 4, 8023, 16, 19, 19, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982674432, 91, 1, 1, 99, 0, 0, 2, 1, 0, 0, 12, 8041, 33, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982739968, 92, 1, 1, 112, 0, 0, 2, 1, 0, 0, 5, 8023, 16, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982805504, 93, 1, 1, 18, 0, 0, 2, 1, 0, 0, 7, 8035, 28, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982871040, 94, 1, 1, 0, 0, 0, 2, 1, 0, 0, 6, 8058, 17, 48, 12, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474982936576, 95, 1, 1, 0, 0, 0, 2, 1, 0, 0, 9, 10326, 24, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474983002112, 96, 1, 1, 0, 0, 0, 2, 1, 0, 0, 10, 16323, 33, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474983067648, 97, 1, 1, 3, 0, 0, 2, 1, 0, 0, 6, 284, 21, 16, 16, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (281474983133184, 98, 1, 1, 8, 0, 0, 2, 1, 0, 0, 9, 1056, 18, 538, 17, 1, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949953880064, 7, 2, 1, 127, 0, 0, 2, 1, 0, 0, 0, 22, 22, 24, 24, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949954535424, 17, 2, 1, 0, 0, 0, 2, 1, 0, 0, 5, 533, 14, 534, 15, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949955190784, 27, 2, 1, 15, 0, 0, 2, 1, 0, 0, 0, 265, 5, 267, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949955649536, 34, 2, 1, 124, 0, 0, 2, 1, 0, 0, 0, 270, 10, 272, 12, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949956108288, 41, 2, 1, 567, 0, 0, 2, 1, 0, 0, 4, 274, 11, 276, 13, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949956304896, 44, 2, 1, 1, 0, 0, 2, 1, 0, 0, 0, 270, 10, 272, 12, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949956435968, 46, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 265, 5, 267, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949956698112, 50, 2, 1, 34, 0, 0, 2, 1, 0, 0, 0, 269, 9, 271, 11, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949956763648, 51, 2, 1, 0, 0, 0, 0, 1, 0, 0, 4, 273, 10, 275, 0, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949956960256, 54, 2, 1, 285, 0, 0, 2, 1, 0, 0, 3, 272, 9, 274, 11, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949957025792, 55, 2, 1, 445, 0, 0, 2, 1, 0, 0, 0, 17, 17, 23, 23, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949957222400, 58, 2, 1, 23, 0, 0, 2, 1, 0, 0, 0, 270, 10, 272, 12, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949957615616, 64, 2, 1, 16, 0, 0, 2, 1, 0, 0, 0, 266, 6, 268, 8, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949957812224, 67, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 265, 5, 267, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949957943296, 69, 2, 1, 1, 0, 0, 2, 1, 0, 0, 3, 782, 5, 788, 11, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949958270976, 74, 2, 1, 215, 0, 0, 0, 1, 0, 0, 0, 21, 18, 27, 0, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949958336512, 75, 2, 1, 132, 0, 0, 0, 1, 0, 0, 0, 21, 18, 27, 0, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949958533120, 78, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 26, 26, 24, 24, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949959319552, 90, 2, 1, 97, 0, 0, 2, 1, 0, 0, 0, 13, 13, 15, 11, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949959385088, 91, 2, 1, 99, 0, 0, 2, 1, 0, 0, 0, 23, 23, 25, 25, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949959516160, 93, 2, 1, 18, 0, 0, 2, 1, 0, 0, 0, 13, 13, 19, 19, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949959647232, 95, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 265, 5, 267, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949959712768, 96, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 265, 5, 267, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949959778304, 97, 2, 1, 3, 0, 0, 2, 1, 0, 0, 0, 270, 10, 272, 12, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (562949959843840, 98, 2, 1, 8, 0, 0, 2, 1, 0, 0, 6, 532, 11, 538, 17, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424931246080, 17, 3, 1, 0, 0, 0, 2, 1, 0, 0, 0, 265, 5, 267, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424931901440, 27, 3, 1, 15, 0, 0, 0, 1, 0, 0, 2, 97, 5, 103, 0, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424932360192, 34, 3, 1, 124, 0, 0, 2, 1, 0, 0, 0, 270, 10, 272, 12, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424933146624, 46, 3, 1, 0, 0, 0, 2, 1, 0, 0, 0, 911, 5, 913, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424933408768, 50, 3, 1, 34, 0, 0, 2, 1, 0, 0, 0, 269, 9, 271, 11, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424934522880, 67, 3, 1, 0, 0, 0, 2, 1, 0, 0, 3, 528, 9, 530, 11, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424934653952, 69, 3, 1, 1, 0, 0, 2, 1, 0, 0, 0, 265, 5, 267, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424936357888, 95, 3, 1, 0, 0, 0, 2, 1, 0, 0, 0, 41, 5, 43, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (844424936423424, 96, 3, 1, 0, 0, 0, 2, 1, 0, 0, 4, 37, 10, 43, 16, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (1125899909070848, 34, 4, 1, 124, 0, 0, 0, 0, 0, 0, 0, 13, 10, 19, 0, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (1125899909857280, 46, 4, 1, 0, 0, 0, 2, 1, 0, 0, 0, 41, 5, 43, 7, 0, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594037993472, 1993058136, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 47, 47, 53, 53, 0, 1, 0, 0, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038124544, 2025058250, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 47, 47, 53, 53, 0, 1, 0, 0, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038255616, 2057058364, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 47, 47, 53, 53, 0, 1, 0, 0, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038321152, 2073058421, 1, 1, 0, 0, 0, 2, 1, 0, 0, 9, 596, 68, 19, 19, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038386688, 2073058421, 2, 1, 0, 0, 0, 2, 0, 0, 0, 6, 52, 49, 58, 55, 1, 1, 1, 0, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038452224, 2089058478, 1, 1, 0, 0, 0, 2, 1, 0, 0, 6, 51, 48, 23, 23, 0, 1, 1, 1, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038517760, 2089058478, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 21, 21, 15, 15, 0, 1, 1, 0, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038583296, 1993058136, 1, 1, 0, 0, 0, 2, 1, 0, 0, 15, 8108, 100, 49, 49, 0, 1, 1, 1, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038648832, 2025058250, 1, 1, 0, 0, 0, 2, 1, 0, 0, 15, 8108, 100, 49, 49, 0, 1, 1, 1, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038714368, 2057058364, 1, 1, 0, 0, 0, 2, 1, 0, 0, 15, 8108, 100, 49, 49, 0, 1, 1, 1, 1, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038779904, 2105058535, 1, 1, 40, 0, 0, 2, 1, 0, 0, 3, 117, 10, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038845440, 2137058649, 1, 1, 3, 0, 0, 2, 1, 0, 0, 2, 115, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038910976, 21575115, 1, 1, 3, 0, 0, 2, 1, 0, 0, 2, 35, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594038976512, 53575229, 1, 1, 7, 0, 0, 2, 1, 0, 0, 2, 115, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039042048, 85575343, 1, 1, 17, 0, 0, 2, 1, 0, 0, 2, 115, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039107584, 117575457, 1, 1, 18, 0, 0, 2, 1, 0, 0, 2, 115, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039173120, 149575571, 1, 1, 3, 0, 0, 2, 1, 0, 0, 2, 35, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039238656, 181575685, 1, 1, 15, 0, 0, 2, 1, 0, 0, 2, 115, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039304192, 213575799, 1, 1, 3, 0, 0, 2, 1, 0, 0, 2, 63, 6, 15, 9, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039369728, 245575913, 1, 1, 51, 0, 0, 2, 1, 0, 0, 2, 115, 8, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039435264, 277576027, 1, 1, 44, 0, 0, 2, 1, 0, 0, 2, 15, 12, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039500800, 309576141, 1, 1, 36, 0, 0, 2, 1, 0, 0, 17, 1876, 49, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039566336, 341576255, 1, 1, 0, 0, 0, 2, 1, 0, 0, 3, 23, 20, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039631872, 373576369, 1, 1, 40, 0, 0, 2, 1, 0, 0, 2, 15, 12, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039697408, 405576483, 1, 1, 45, 0, 0, 2, 1, 0, 0, 2, 15, 12, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039762944, 437576597, 1, 1, 57, 0, 0, 2, 1, 0, 0, 2, 15, 12, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039828480, 469576711, 1, 1, 14, 0, 0, 2, 1, 0, 0, 2, 15, 12, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039894016, 501576825, 1, 1, 7, 0, 0, 2, 1, 0, 0, 5, 143, 14, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594039959552, 533576939, 1, 1, 0, 0, 0, 2, 1, 0, 0, 2, 15, 12, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594040025088, 565577053, 1, 1, 5, 0, 0, 2, 1, 0, 0, 3, 119, 12, 15, 15, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594040090624, 933578364, 1, 1, 0, 0, 0, 2, 1, 0, 0, 5, 8281, 16, 15, 11, 0, 1, 1, 1, 0, null);
INSERT INTO sys.system_internals_partitions (partition_id, object_id, index_id, partition_number, rows, filestream_filegroup_id, is_orphaned, dropped_lob_column_state, is_unique, is_replicated, is_logged_for_replication, max_null_bit_used, max_leaf_length, min_leaf_length, max_internal_length, min_internal_length, allows_nullable_keys, allow_row_locks, allow_page_locks, is_data_row_format, is_not_versioned, filestream_guid) VALUES (72057594040156160, 933578364, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 269, 9, 271, 11, 0, 1, 1, 0, 0, null);