CREATE TABLE BD5W6_424P.dbo.Films
(
    NoFilm int PRIMARY KEY NOT NULL,
    AnneeSortie int,
    Categorie int,
    Format int,
    DateMAJ datetime NOT NULL,
    NoUtilisateurMAJ int NOT NULL,
    Resume nvarchar(500),
    DureeMinutes int,
    FilmOriginal bit,
    ImagePochette nvarchar(50),
    NbDisques int,
    TitreFrancais nvarchar(50) NOT NULL,
    TitreOriginal nvarchar(50),
    VersionEtendue bit,
    NoRealisateur int,
    NoProducteur int,
    XTra nvarchar(255),
    CONSTRAINT FK_Films_Categories FOREIGN KEY (Categorie) REFERENCES BD5W6_424P.dbo.Categories (NoCategorie),
    CONSTRAINT FK_Films_Formats FOREIGN KEY (Format) REFERENCES BD5W6_424P.dbo.Formats (NoFormat),
    CONSTRAINT FK_Films_Utilisateurs FOREIGN KEY (NoUtilisateurMAJ) REFERENCES BD5W6_424P.dbo.Utilisateurs (NoUtilisateur),
    CONSTRAINT FK_Films_Realisateurs FOREIGN KEY (NoRealisateur) REFERENCES BD5W6_424P.dbo.Realisateurs (NoRealisateur),
    CONSTRAINT FK_Films_Producteurs FOREIGN KEY (NoProducteur) REFERENCES BD5W6_424P.dbo.Producteurs (NoProducteur)
);
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181001, 1979, 20, 3, '2018-10-01 00:00:00.000', 3, 'Le capitaine Willard (Martin Sheen) est envoyé au Cambodge avec pour mission d''exécuter le colonel Kurtz (Marlon Brando), un officier américain déserteur qui a perdu la raison et s''est improvisé souverain d''une tribu indigène. En descendant la rivière qui le mènera à son but, Willard rencontre le lieutenant colonel Kilgore (Robert Duvall) dont l''amour de la guerre n''a d''égal que sa passion pour le " surf ".', 217, null, '171001.jpg', 3, 'C''est l''apocalypse', 'Apocalypse now', 1, 1, 1, 'http://www.cinemamontreal.com/films/3114/C_est_l_Apocalypse.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181002, 2004, 15, 3, '2018-10-01 00:00:00.000', 4, 'En 2035, la couche d''ozone a été détruite par le gaz carbonique des voitures, l''industrie chimique et le pouch-pouch en ca-cane. La Terre cuit sous les rayons du soleil et les compagnies de crême solaire s''enrichissent. Il faut trouver une nouvelle planète pour six milliards de tatas. Le capitaine Charles Patenaude et son équipage s''embarquent ainsi sur le vaisseau spatial Romano Fafard, en route vers les confins de l''univers !', 109, 1, '171002.jpg', 1, 'Dans une galaxie près de chez vous', 'Dans une galaxie près de chez vous', 0, 2, null, 'http://www.cinemamontreal.com/films/5918/Dans_une_galaxie_pres_de_chez_vous.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181003, 2007, 50, 1, '2018-10-01 00:00:00.000', 6, '', 122, 1, '171003.jpg', 1, 'Danny Ocean 13', 'Ocean''s thirteen', 0, 3, 2, 'http://www.cinemamontreal.com/films/10648/Danny_Ocean_13.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181004, 2004, 19, 1, '2018-10-01 00:00:00.000', 6, 'Michael Moore présente avec scepticisme le Président George W. Bush et ses propres conseillers. Prenant pour point de départ l''élection controversée de 2000, le réalisateur retrace l''improbable ascension d''un médiocre pétrolier texan devenu maître du monde libre. Puis il ouvre la boîte de Pandore du Président et révèle les liens personnels et financiers qui unissent la famille Bush à celle de Ben Laden. Michael Moore y dénonce également les méfaits du Patriot Act et les souffrances provoquées pa', 110, 1, '171004.jpg', 1, 'Fahrenheit 9/11 v.f.', 'Fahrenheit 9/11', 0, 4, 3, 'http://www.cinemamontreal.com/films/6399/Fahrenheit_9_11_v_f.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181005, null, null, null, '2018-10-02 00:00:00.000', 2, '', null, null, '', null, 'Opération G-Force', 'G-Force', null, null, null, 'http://www.cinemamontreal.com/films/13879/G-Force.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181006, 2008, 30, 3, '2018-10-02 00:00:00.000', 2, '10 000 ans avant J-C, un homme de 21 et sa tribu luttent pour survivre en chassant les mammouths. Quand les chasseurs de son clan et la princesse dont il est tombé amoureux sont faits prisonniers, il se lance à leur secours...', 109, 1, '171006.jpg', 1, '10 000 av. J.-C.', '10,000 B.C.', 0, 5, 4, 'http://www.cinemamontreal.com/films/10687/10_000_av__J_-C.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181007, null, null, null, '2018-10-05 00:00:00.000', 3, '', null, null, '', null, 'Ghandi', '', null, null, null, 'http://www.cinemamontreal.com/films/3601/Gandhi.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181008, 2005, 30, 3, '2018-10-07 00:00:00.000', 4, '25 décembre 1960: Zachary Beaulieu vient au monde, quatrième d''une famille de cinq garçons. Famille de banlieue sans histoire avec une mère aimante et un père un peu bourru, mais fier de ses garçons. Le début d''une belle enfance, où se succèdent les Noël et les anniversaires avec l''éternel solo du père Beaulieu chantant Aznavour, Emmène-moi au bout de la terre, les séances de lavage de voiture en plein air et les visites au casse-croûte pour Zac, le chouchou de son père pour une fois.', 127, 1, '171008.jpg', 1, 'C.R.A.Z.Y.', 'C.R.A.Z.Y.', 0, 6, 5, 'http://www.cinemamontreal.com/films/8020/C_R_A_Z_Y.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181009, null, null, null, '2018-10-09 00:00:00.000', 3, '', null, null, '', null, 'G.I. Joe: Le réveil du cobra', '', null, null, null, 'http://www.cinemamontreal.com/films/16921/G_I__Joe__Le_reveil_du_cobra.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181010, null, null, null, '2018-10-10 00:00:00.000', 3, '', null, null, '', null, 'Les gangs de New-York', '', null, null, null, 'http://www.cinemamontreal.com/films/2975/Les_Gangs_de_New-York.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181011, 2000, 18, 3, '2018-10-11 00:00:00.000', 6, 'Cruella De Vil (Glenn Close) est libérée de prison pour bonne conduite, avec la promesse que plus jamais elle n''aura affaire avec la fourrure. Promesse rapidement oubliée alors qu''elle échafaude une magouille pour se procurer l''ultime manteau en peaux de dalmatiens.', 100, 1, '', 1, '102 Dalmatiens vf.', '102 Dalmatians', 0, 7, 6, 'http://www.cinemamontreal.com/films/2/102_Dalmatiens_vf.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181012, 2010, 15, 1, '2018-10-23 00:00:00.000', 4, 'Benoit, un comédien qui survit grâce à un emploi de barman, suit le conseil de son frère Frank, un ex-joueur de hockey devenu son agent. Il décide de se faire pousser la barbe pour un rôle dans un souper-spectacle. Sa blonde Vicky, une ex-dramaturge devenue bibliothécaire, accepte mal cette nouvelle lubie car elle retarde leur projet d''acheter le condo de leurs amis Caro et Vincent, qui tiennent un salon de coiffure et d''esthétique. Mais la barbe de Benoit semble magique: il commence à avoir du ', 100, 1, '171012.jpg', 1, 'Le baiser du barbu', 'Le baiser du barbu', 0, 8, 7, 'http://www.cinemamontreal.com/films/36092/Le_Baiser_du_barbu.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181013, 2007, 15, 3, '2018-10-24 00:00:00.000', 2, 'Cadavres raconte, sous la forme d''une comédie cynique résolument moderne, l''éternelle histoire du péché originel. Le jour de la mort de sa mère, Raymond Marchildon appelle à la rescousse Angèle, sa soeur aînée. Il réveille alors la conscience qu''il lui manquait, ainsi que les souvenirs d''un paradis perdu: l''innocence de leur enfance. Le frère et la soeur deviennent rapidement inséparables dans un monde de plus en plus absurde où les cadavres s''accumulent dans le sous-sol de la maison. Voilà que ', 117, 1, '171013.jpg', 1, 'Cadavres', 'Cadavres', 0, 9, 8, 'http://www.cinemamontreal.com/films/12015/Cadavres.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181014, null, null, null, '2018-10-24 00:00:00.000', 2, '', null, null, '', null, 'J''ai tué ma mère', '', null, 10, 9, 'http://www.cinemamontreal.com/films/32791/J_ai_tue_ma_mere.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181101, null, null, null, '2018-11-01 00:00:00.000', 3, '', null, null, '', null, 'Madagascar v.f.', 'Madagascar', null, null, null, 'http://www.cinemamontreal.com/films/7729/Madagascar_v_f.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181102, null, null, null, '2018-11-02 00:00:00.000', 3, '', null, null, '', null, 'Le Parrain', '', null, 1, 10, 'http://www.cinemamontreal.com/films/526/Le_Parrain.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181103, null, null, null, '2018-11-03 00:00:00.000', 3, '', null, null, '', null, 'La Bataille de Passchendaele', '', null, null, null, 'http://www.cinemamontreal.com/films/19063/Passchendaele.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181104, 1957, 30, 2, '2018-11-08 00:00:00.000', 6, '', 96, 1, '171104.jpg', 1, '12 hommes en colère', '12 angry men', 0, 11, 11, 'http://www.cinemamontreal.com/films/3546/12_Hommes_En_Colere.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181105, 2005, 50, 1, '2018-11-13 00:00:00.000', 3, 'Jack Starks (Adrian Brody) est très chanceux lorsqu''il échappe miraculeusement à la mort lors de la guerre du Golf et retourne dans son pays natal. Malheureusement, sa cicatrice de guerre c''est l''amnésie, ce qui l''empêche, alors qu''il est accusé de meurtre, de se défendre. Il échoue dans un asile où un docteur (Kris Kristofferson) développe, pour éliminer les instincts criminels, un traitement expérimental à base d''un cocktail médicamenteux. Enfermé dans un caisson, ce traitement va le faire voy', 102, 1, '171105.jpg', 1, 'La camisole de force', 'The jacket', 0, 12, 12, 'http://www.cinemamontreal.com/films/7708/La_Camisole_de_force.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181106, null, null, null, '2018-11-14 00:00:00.000', 3, '', null, null, '', null, 'La passion du Christ', '', null, null, null, 'http://www.cinemamontreal.com/films/5811/La_Passion_du_Christ.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181107, 1994, 30, 3, '2018-11-15 00:00:00.000', 2, '', 142, 1, '171107.jpg', 2, 'À l''ombre de Shawshank', 'The Shawshank Redemption', 0, 13, 13, 'http://www.cinemamontreal.com/films/1194/A_l_ombre_de_Shawshank.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181108, null, null, null, '2018-11-16 00:00:00.000', 3, '', null, 0, '', null, 'Hary Potter et les reliques de la mort : Partie 1', '', null, null, null, 'http://www.cinemamontreal.com/films/21868/Harry_Potter_et_les_reliques_de_la_mort__Partie_1.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181109, null, null, null, '2018-11-17 00:00:00.000', 3, '', null, null, '', null, 'La saga Twilight : Hésitation', '', null, null, null, 'http://www.cinemamontreal.com/films/35777/La_Saga_Twilight__Hesitation.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181110, null, null, null, '2018-11-17 00:00:00.000', 2, '', null, null, '', null, 'Le Seigneur des Anneaux: La Communauté de l''Anneau', '', null, null, 14, 'http://www.cinemamontreal.com/films/2046/Le_Seigneur_des_Anneaux__La_Communaute_de_l_Anneau.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181111, null, null, null, '2018-11-18 00:00:00.000', 6, '', null, null, '', null, 'Le Seigneur des anneaux: le retour du roi ', '', null, null, 14, 'http://www.cinemamontreal.com/films/4965/Le_Seigneur_des_anneaux__le_retour_du_roi.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181112, 1998, 44, 3, '2018-11-19 00:00:00.000', 4, 'Nous sommes au 16e sciècle. Danielle est une jeune femme, qui aime lire, et qui est capable de citer facilement des extraits d''Utopia de Thomas Moore. Elle en possede assez de charme pour capturer le coeur d''un prince... après l''avoir tiré de son cheval avec une pomme.', 121, 1, '171112.jpg', 1, 'À Tout Jamais', 'Ever After', 0, 14, null, 'http://www.cinemamontreal.com/films/435/A_Tout_Jamais.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181113, null, null, null, '2018-11-20 00:00:00.000', 3, '', null, null, '', null, 'Le Seigneur des Anneaux: Les Deux Tours', '', null, null, 14, 'http://www.cinemamontreal.com/films/3671/Le_Seigneur_des_Anneaux__Les_Deux_Tours.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181114, 2010, 15, 1, '2018-11-21 00:00:00.000', 3, 'Quatre soldats américains sont arrêtés au Moyen-Orient suite à une mission secrète. Ils s''échappent de la prison militaire pour monter une équipe de mercenaires du bien.', 117, 1, '171114.jpg', 1, 'L''Agence tous risques', 'The A-Team', 0, 15, 15, 'http://www.cinemamontreal.com/films/20568/L_Agence_tous_risques.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181115, null, null, null, '2018-11-22 00:00:00.000', 6, '', null, null, '', null, 'Les Sept jours du Talion', '', null, null, null, 'http://www.cinemamontreal.com/films/34235/Les_Sept_jours_du_Talion.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181116, null, null, null, '2018-11-23 00:00:00.000', 3, '', null, 0, '', null, 'Lance et compte', '', null, null, null, 'http://www.lanceetcompte-lefilm.ca/');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181117, 2008, 38, 1, '2018-11-24 00:00:00.000', 6, 'Un couple est hanté par un esprit démoniaque.', 99, 1, '171117.jpg', 1, 'Activité paranormale', 'Paranormal Activity', 0, 16, 16, 'http://www.cinemamontreal.com/films/19213/Activite_paranormale.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181118, 2008, 15, 3, '2018-11-25 00:00:00.000', 4, 'Convaincus du bien-fondé de leur mission (et aussi parce qu''ils n''avaient rien d''autre à faire ce jour-là), les membres de l''équipage du vaisseau Romano Fafard explorent de nouvelles galaxies à la recherche d''une planète habitable où déménager les Terriens. Toutefois, cette exploration tourne court suite à la perte accidentelle de la seule sonde qui leur reste. Selon les calculs de Flavien, la sonde se serait écrasée sur la planète "Crème hydratante pour le visage - soulage la peau sèche". Le Ca', 100, 1, '171118.jpg', 1, 'Dans une galaxie près de chez vous 2', 'Dans une galaxie près de chez vous 2', 0, 17, null, 'http://www.cinemamontreal.com/films/18091/Dans_une_galaxie_pres_de_chez_vous_2.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181119, null, null, null, '2018-11-26 00:00:00.000', 3, '', null, null, '', null, 'T''choupi, le film', '', null, null, null, 'http://www.cinemamontreal.com/films/7712/T_choupi__le_film.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181201, 2007, 11, 1, '2018-12-01 00:00:00.000', 2, 'Une histoire d''amour qui se déroule au milieu des années 60 et des manifestations anti-guerre, de la lutte pour la liberté d''expression et les droits civiques, l''exploration des esprits et le rock''n roll. Le film nous fait voyager des Universités du Massachussetts et de l''Ohio, aux émeutes de Détroit et aux champs de batailles du Vietnam, en passant par les docks de Liverpool. Les amants Jude (Jim Sturgess) et Lucy (Evan Rachel Wood) se retrouvent, en compagnie d''une bande de musiciens et d''amis', 133, 1, '171201.jpg', 1, 'À travers l''univers', 'Across the Universe', 0, 18, 17, 'http://www.cinemamontreal.com/films/11057/A_travers_l_univers.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181202, null, null, null, '2018-12-02 00:00:00.000', 6, '', null, null, '', null, 'Le tambour', '', null, null, null, 'http://www.cinemamontreal.com/films/3173/Le_Tambour.html');
INSERT INTO BD5W6_424P.dbo.Films (NoFilm, AnneeSortie, Categorie, Format, DateMAJ, NoUtilisateurMAJ, Resume, DureeMinutes, FilmOriginal, ImagePochette, NbDisques, TitreFrancais, TitreOriginal, VersionEtendue, NoRealisateur, NoProducteur, XTra) VALUES (181203, null, null, null, '2018-12-03 00:00:00.000', 6, '', null, null, '', null, 'V for Vendetta', '', null, null, null, 'http://www.cinemamontreal.com/films/8531/V_for_Vendetta.html');