CREATE TABLE sys.dm_exec_requests
(
    session_id smallint NOT NULL,
    request_id int NOT NULL,
    start_time datetime NOT NULL,
    status nvarchar(30) NOT NULL,
    command nvarchar(16) NOT NULL,
    sql_handle varbinary(64),
    statement_start_offset int,
    statement_end_offset int,
    plan_handle varbinary(64),
    database_id smallint NOT NULL,
    user_id int NOT NULL,
    connection_id uniqueidentifier,
    blocking_session_id smallint,
    wait_type nvarchar(60),
    wait_time int NOT NULL,
    last_wait_type nvarchar(60) NOT NULL,
    wait_resource nvarchar(256) NOT NULL,
    open_transaction_count int NOT NULL,
    open_resultset_count int NOT NULL,
    transaction_id bigint NOT NULL,
    context_info varbinary(128),
    percent_complete real NOT NULL,
    estimated_completion_time bigint NOT NULL,
    cpu_time int NOT NULL,
    total_elapsed_time int NOT NULL,
    scheduler_id int,
    task_address varbinary(8),
    reads bigint NOT NULL,
    writes bigint NOT NULL,
    logical_reads bigint NOT NULL,
    text_size int NOT NULL,
    language nvarchar(128),
    date_format nvarchar(3),
    date_first smallint NOT NULL,
    quoted_identifier bit NOT NULL,
    arithabort bit NOT NULL,
    ansi_null_dflt_on bit NOT NULL,
    ansi_defaults bit NOT NULL,
    ansi_warnings bit NOT NULL,
    ansi_padding bit NOT NULL,
    ansi_nulls bit NOT NULL,
    concat_null_yields_null bit NOT NULL,
    transaction_isolation_level smallint NOT NULL,
    lock_timeout int NOT NULL,
    deadlock_priority int NOT NULL,
    row_count bigint NOT NULL,
    prev_error int NOT NULL,
    nest_level int NOT NULL,
    granted_query_memory int NOT NULL,
    executing_managed_code bit NOT NULL,
    group_id int NOT NULL,
    query_hash binary(8),
    query_plan_hash binary(8)
);
INSERT INTO sys.dm_exec_requests (session_id, request_id, start_time, status, command, sql_handle, statement_start_offset, statement_end_offset, plan_handle, database_id, user_id, connection_id, blocking_session_id, wait_type, wait_time, last_wait_type, wait_resource, open_transaction_count, open_resultset_count, transaction_id, context_info, percent_complete, estimated_completion_time, cpu_time, total_elapsed_time, scheduler_id, task_address, reads, writes, logical_reads, text_size, language, date_format, date_first, quoted_identifier, arithabort, ansi_null_dflt_on, ansi_defaults, ansi_warnings, ansi_padding, ansi_nulls, concat_null_yields_null, transaction_isolation_level, lock_timeout, deadlock_priority, row_count, prev_error, nest_level, granted_query_memory, executing_managed_code, group_id, query_hash, query_plan_hash) VALUES (51, 0, '2018-11-14 12:42:15.023', 'running', 'SELECT', 0x02000000FDA044129BAB8D170F59EC2B7557E0D6D92D6EA7, 0, -1, 0x06002E00FDA0441240017024010000000000000000000000, 46, 5, 'C415C89E-3C71-42A3-9D04-4793F9ADC458', 0, null, 0, 'SOS_SCHEDULER_YIELD', '', 0, 1, 1237402196, 0x, 0, 0, 0, 56, 0, 0x00000000C847C2C8, 0, 0, 113, -1, 'us_english', 'mdy', 7, 1, 0, 1, 0, 1, 1, 1, 1, 2, -1, 0, 1, 0, 0, 0, 0, 1, 0x3699BA96D3F9F6A1, 0xAD412BC185253225);