CREATE TABLE sys.xml_schema_components
(
    xml_component_id int NOT NULL,
    xml_collection_id int NOT NULL,
    xml_namespace_id int NOT NULL,
    is_qualified bit NOT NULL,
    name nvarchar(4000),
    symbol_space char(1) NOT NULL,
    symbol_space_desc nvarchar(60),
    kind char(1) NOT NULL,
    kind_desc nvarchar(60),
    derivation char(1) NOT NULL,
    derivation_desc nvarchar(60),
    base_xml_component_id int,
    scoping_xml_component_id int
);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (6, 1, 1, 1, 'anyType', 'T', 'TYPE', 'N', 'ANY_TYPE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (11, 1, 1, 1, 'anySimpleType', 'T', 'TYPE', 'Z', 'ANY_SIMPLE_TYPE', 'R', 'RESTRICTION', 6, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (15, 1, 1, 1, 'string', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (16, 1, 1, 1, 'boolean', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (17, 1, 1, 1, 'float', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (18, 1, 1, 1, 'double', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (19, 1, 1, 1, 'decimal', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (20, 1, 1, 1, 'duration', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (21, 1, 1, 1, 'dateTime', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (22, 1, 1, 1, 'time', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (23, 1, 1, 1, 'date', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (24, 1, 1, 1, 'gYearMonth', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (25, 1, 1, 1, 'gYear', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (26, 1, 1, 1, 'gMonthDay', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (27, 1, 1, 1, 'gDay', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (28, 1, 1, 1, 'gMonth', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (29, 1, 1, 1, 'hexBinary', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (30, 1, 1, 1, 'base64Binary', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (31, 1, 1, 1, 'anyURI', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (32, 1, 1, 1, 'QName', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (33, 1, 1, 1, 'NOTATION', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (100, 1, 1, 1, 'normalizedString', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (101, 1, 1, 1, 'token', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 100, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (102, 1, 1, 1, 'language', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 101, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (103, 1, 1, 1, 'Name', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 101, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (104, 1, 1, 1, 'NCName', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 103, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (105, 1, 1, 1, 'ID', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 104, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (106, 1, 1, 1, 'IDREF', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 104, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (107, 1, 1, 1, 'ENTITY', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 104, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (108, 1, 1, 1, 'NMTOKEN', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 101, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (109, 1, 1, 1, 'integer', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (110, 1, 1, 1, 'nonPositiveInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 109, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (111, 1, 1, 1, 'negativeInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 110, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (112, 1, 1, 1, 'long', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 109, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (113, 1, 1, 1, 'int', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 112, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (114, 1, 1, 1, 'short', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 113, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (115, 1, 1, 1, 'byte', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 114, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (116, 1, 1, 1, 'nonNegativeInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 109, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (117, 1, 1, 1, 'unsignedLong', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 116, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (118, 1, 1, 1, 'unsignedInt', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 117, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (119, 1, 1, 1, 'unsignedShort', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 118, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (120, 1, 1, 1, 'unsignedByte', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 119, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (121, 1, 1, 1, 'positiveInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 116, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (200, 1, 1, 1, 'IDREFS', 'T', 'TYPE', 'L', 'LIST_TYPE', 'R', 'RESTRICTION', 106, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (201, 1, 1, 1, 'ENTITIES', 'T', 'TYPE', 'L', 'LIST_TYPE', 'R', 'RESTRICTION', 107, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (202, 1, 1, 1, 'NMTOKENS', 'T', 'TYPE', 'L', 'LIST_TYPE', 'R', 'RESTRICTION', 108, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (260, 1, 3, 1, 'lang', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (261, 1, 3, 1, 'base', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (262, 1, 3, 1, 'space', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (263, 1, 3, 1, 'xmlSpaceEnum', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (300, 1, 2, 1, 'sqlDbTypeEnum', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (301, 1, 2, 1, 'sqlCompareOptionsEnum', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (302, 1, 2, 1, 'sqlCompareOptionsList', 'T', 'TYPE', 'L', 'LIST_TYPE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (303, 1, 2, 1, 'char', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (304, 1, 2, 1, 'nchar', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (305, 1, 2, 1, 'varchar', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (306, 1, 2, 1, 'nvarchar', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (307, 1, 2, 1, 'text', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (308, 1, 2, 1, 'ntext', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (309, 1, 2, 1, 'varbinary', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (310, 1, 2, 1, 'binary', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (311, 1, 2, 1, 'image', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (312, 1, 2, 1, 'timestamp', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (313, 1, 2, 1, 'timestampNumeric', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 112, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (314, 1, 2, 1, 'decimal', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (315, 1, 2, 1, 'numeric', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (316, 1, 2, 1, 'bigint', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 112, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (317, 1, 2, 1, 'int', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 113, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (318, 1, 2, 1, 'smallint', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 114, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (319, 1, 2, 1, 'tinyint', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 120, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (320, 1, 2, 1, 'bit', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 16, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (321, 1, 2, 1, 'float', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 18, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (322, 1, 2, 1, 'real', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 17, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (324, 1, 2, 1, 'datetime', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (325, 1, 2, 1, 'smalldatetime', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (326, 1, 2, 1, 'money', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (327, 1, 2, 1, 'smallmoney', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (328, 1, 2, 1, 'uniqueidentifier', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (329, 1, 2, 1, 'xml', 'T', 'TYPE', 'K', 'COMPLEX_TYPE', 'R', 'RESTRICTION', 6, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (330, 1, 2, 1, 'date', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 23, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (331, 1, 2, 1, 'time', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 22, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (332, 1, 2, 1, 'datetime2', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (333, 1, 2, 1, 'datetimeoffset', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (334, 1, 2, 1, 'hierarchyid', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (360, 1, 2, 1, 'dbobject', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 31, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (361, 1, 2, 1, 'sqlDbType', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (362, 1, 2, 1, 'clrTypeName', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (363, 1, 2, 1, 'maxLength', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (364, 1, 2, 1, 'localeId', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (365, 1, 2, 1, 'sqlCompareOptions', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (366, 1, 2, 1, 'sqlCollationVersion', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (367, 1, 2, 1, 'sqlSortId', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (368, 1, 2, 1, 'scale', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (369, 1, 2, 1, 'precision', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (370, 1, 2, 1, 'xmlSchemaCollection', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (371, 1, 2, 1, 'sqlTypeAlias', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (372, 1, 2, 1, 'base64Encoded', 'A', 'ATTRIBUTE', 'A', 'ATTRIBUTE', 'N', 'NONE', null, null);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (380, 1, 2, 0, null, 'M', 'MODEL_GROUP', 'M', 'MODEL_GROUP', 'N', 'NONE', null, 329);
INSERT INTO sys.xml_schema_components (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id) VALUES (381, 1, 2, 0, null, 'N', 'NONE', 'W', 'ELEMENT_WILDCARD', 'N', 'NONE', null, 380);