CREATE TABLE sys.dm_repl_articles
(
    artcache_db_address varbinary(8),
    artcache_table_address varbinary(8),
    artcache_schema_address varbinary(8),
    artcache_article_address varbinary(8),
    artid int,
    artfilter int,
    artobjid int,
    artpubid int,
    artstatus tinyint,
    arttype tinyint,
    wszArtdesttable nvarchar(256),
    wszArtdesttableowner nvarchar(256),
    wszArtinscmd nvarchar(258),
    cmdTypeIns int,
    wszArtdelcmd nvarchar(258),
    cmdTypeDel int,
    wszArtupdcmd nvarchar(258),
    cmdTypeUpd int,
    wszArtpartialupdcmd nvarchar(258),
    cmdTypePartialUpd int,
    numcol int,
    artcmdtype tinyint,
    artgeninscmd nvarchar(4000),
    artgendelcmd nvarchar(4000),
    artgenupdcmd nvarchar(4000),
    artpartialupdcmd nvarchar(4000),
    artupdtxtcmd nvarchar(4000),
    artgenins2cmd nvarchar(4000),
    artgendel2cmd nvarchar(4000),
    fInReconcile tinyint,
    fPubAllowUpdate tinyint,
    intPublicationOptions int
);