CREATE TABLE sys.indexes
(
    object_id int NOT NULL,
    name sysname,
    index_id int NOT NULL,
    type tinyint NOT NULL,
    type_desc nvarchar(60),
    is_unique bit,
    data_space_id int NOT NULL,
    ignore_dup_key bit,
    is_primary_key bit,
    is_unique_constraint bit,
    fill_factor tinyint NOT NULL,
    is_padded bit,
    is_disabled bit,
    is_hypothetical bit,
    allow_row_locks bit,
    allow_page_locks bit,
    has_filter bit,
    filter_definition nvarchar(max)
);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (3, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (5, 'clust', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (7, 'clust', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (7, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (8, null, 0, 0, 'HEAP', 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (17, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (17, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (17, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (19, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (23, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (24, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (25, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (27, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (27, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (27, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (29, 'clust', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (34, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (34, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (34, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (34, 'nc3', 4, 2, 'NONCLUSTERED', 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (41, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (41, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (44, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (44, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (46, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (46, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (46, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (46, 'nc3', 4, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (49, 'clust', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (50, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (50, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (50, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (51, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (51, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (54, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (54, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (55, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (55, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (58, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (58, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (59, 'clust', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (60, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (64, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (64, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (65, 'clust', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (67, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (67, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (67, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (68, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (69, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (69, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (69, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (71, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (72, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (73, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (74, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (74, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (75, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (75, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (78, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (78, 'nc', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (82, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (85, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (90, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (90, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (91, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (91, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (92, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (93, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (93, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (94, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (95, 'cl', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (95, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (95, 'nc3', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (96, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (96, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (96, 'nc2', 3, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (97, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (97, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (98, 'clst', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (98, 'nc1', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (21575115, 'PK_Langues', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (53575229, 'PK_Preferences', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (85575343, 'PK_Producteurs', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (117575457, 'PK_Realisateurs', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (149575571, 'PK_SousTitres', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (181575685, 'PK_Supplements', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (213575799, 'PK_TypesUtilisateur', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (245575913, 'PK_Categories', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (277576027, 'PK_FilmsActeurs', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (309576141, 'PK_Films', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (341576255, 'PK_EmpruntsFilms', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (373576369, 'PK_FilmsSousTitres', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (405576483, 'PK_FilmsSupplements', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (437576597, 'PK_FilmsLangues', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (469576711, 'PK_UtilisateursPreferences', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (501576825, 'PK_Utilisateurs', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (533576939, 'PK_Exemplaires_1', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (565577053, 'PK_ValeursPreferences', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (933578364, 'PK__sysdiagr__C2B05B61398D8EEE', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (933578364, 'UK_principal_name', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (1993058136, 'queue_clustered_index', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (1993058136, 'queue_secondary_index', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2025058250, 'queue_clustered_index', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2025058250, 'queue_secondary_index', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2057058364, 'queue_clustered_index', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2057058364, 'queue_secondary_index', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2073058421, 'FSTSClusIdx', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2073058421, 'FSTSNCIdx', 2, 2, 'NONCLUSTERED', 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2089058478, 'ci_commit_ts', 1, 1, 'CLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2089058478, 'si_xdes_id', 2, 2, 'NONCLUSTERED', 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2105058535, 'PK_Acteurs', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);
INSERT INTO sys.indexes (object_id, name, index_id, type, type_desc, is_unique, data_space_id, ignore_dup_key, is_primary_key, is_unique_constraint, fill_factor, is_padded, is_disabled, is_hypothetical, allow_row_locks, allow_page_locks, has_filter, filter_definition) VALUES (2137058649, 'PK_Formats', 1, 1, 'CLUSTERED', 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, null);