CREATE TABLE INFORMATION_SCHEMA.DOMAINS
(
    DOMAIN_CATALOG nvarchar(128),
    DOMAIN_SCHEMA nvarchar(128),
    DOMAIN_NAME sysname NOT NULL,
    DATA_TYPE nvarchar(128),
    CHARACTER_MAXIMUM_LENGTH int,
    CHARACTER_OCTET_LENGTH int,
    COLLATION_CATALOG sysname,
    COLLATION_SCHEMA sysname,
    COLLATION_NAME sysname,
    CHARACTER_SET_CATALOG sysname,
    CHARACTER_SET_SCHEMA sysname,
    CHARACTER_SET_NAME sysname,
    NUMERIC_PRECISION tinyint,
    NUMERIC_PRECISION_RADIX smallint,
    NUMERIC_SCALE int,
    DATETIME_PRECISION smallint,
    DOMAIN_DEFAULT nvarchar(4000)
);