CREATE TABLE sys.master_files
(
    database_id int NOT NULL,
    file_id int NOT NULL,
    file_guid uniqueidentifier,
    type tinyint NOT NULL,
    type_desc nvarchar(60),
    data_space_id int NOT NULL,
    name sysname NOT NULL,
    physical_name nvarchar(260) NOT NULL,
    state tinyint,
    state_desc nvarchar(60),
    size int NOT NULL,
    max_size int NOT NULL,
    growth int NOT NULL,
    is_media_read_only bit NOT NULL,
    is_read_only bit NOT NULL,
    is_sparse bit NOT NULL,
    is_percent_growth bit NOT NULL,
    is_name_reserved bit NOT NULL,
    create_lsn numeric(25),
    drop_lsn numeric(25),
    read_only_lsn numeric(25),
    read_write_lsn numeric(25),
    differential_base_lsn numeric(25),
    differential_base_guid uniqueidentifier,
    differential_base_time datetime,
    redo_start_lsn numeric(25),
    redo_start_fork_guid uniqueidentifier,
    redo_target_lsn numeric(25),
    redo_target_fork_guid uniqueidentifier,
    backup_lsn numeric(25)
);