CREATE TABLE BD5W6_424P.dbo.Categories
(
    NoCategorie int PRIMARY KEY NOT NULL,
    Description nvarchar(50) NOT NULL
);
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (1, 'Action');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (2, 'Adolescent');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (3, 'Biographie');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (4, 'Cape et d''épée');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (5, 'Catastrophe');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (6, 'Chronique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (7, 'Comédie de moeurs');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (8, 'Comédie d''horreur');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (9, 'Comédie dramatique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (10, 'Comédie fantaisiste');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (11, 'Comédie musicale');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (12, 'Comédie policière');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (13, 'Comédie satirique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (14, 'Comédie sentimentale');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (15, 'Comédie');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (16, 'Criminel');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (17, 'Danse');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (18, 'Dessins animés');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (19, 'Documentaire');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (20, 'Drame de guerre');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (21, 'Drame de moeurs');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (22, 'Drame d''horreur');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (23, 'Drame judiciaire');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (24, 'Drame musical');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (25, 'Drame poétique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (26, 'Drame policier');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (27, 'Drame psychologique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (28, 'Drame sentimental');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (29, 'Drame social');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (30, 'Drame');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (31, 'Espionnage');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (32, 'Expérimental');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (33, 'Fantastique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (34, 'Film à sketches');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (35, 'Film d''animation');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (36, 'Film d''art martial');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (37, 'Historique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (38, 'Horreur');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (39, 'Humoristique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (40, 'Marionnettes');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (41, 'Mélodrame');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (42, 'Musical');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (43, 'Road movie');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (44, 'Romantique');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (45, 'Science-fiction');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (46, 'Série policière');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (47, 'Série TV');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (48, 'Spectacle d''humour');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (49, 'Spectacle musical');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (50, 'Suspense');
INSERT INTO BD5W6_424P.dbo.Categories (NoCategorie, Description) VALUES (51, 'Western');