CREATE TABLE sys.dm_audit_class_type_map
(
    class_type varchar(2),
    class_type_desc nvarchar(35),
    securable_class_desc nvarchar(35)
);
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('DB', 'DATABASE', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('OB', 'OBJECT', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('TY', 'TYPE', 'TYPE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SC', 'SCHEMA', 'SCHEMA');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SX', 'XML SCHEMA COLLECTION', 'XML SCHEMA COLLECTION');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AS', 'ASSEMBLY', 'ASSEMBLY');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('US', 'USER', 'USER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('RL', 'ROLE', 'ROLE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AR', 'APPLICATION ROLE', 'APPLICATION ROLE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('MT', 'MESSAGE TYPE', 'MESSAGE TYPE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('CT', 'CONTRACT', 'CONTRACT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SV', 'SERVICE', 'SERVICE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('BN', 'REMOTE SERVICE BINDING', 'REMOTE SERVICE BINDING');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('RT', 'ROUTE', 'ROUTE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('FC', 'FULLTEXT CATALOG', 'FULLTEXT CATALOG');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('FL', 'FULLTEXT STOPLIST', 'FULLTEXT STOPLIST');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SK', 'SYMMETRIC KEY', 'SYMMETRIC KEY');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('CR', 'CERTIFICATE', 'CERTIFICATE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AK', 'ASYMMETRIC KEY', 'ASYMMETRIC KEY');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SR', 'SERVER', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('EP', 'ENDPOINT', 'ENDPOINT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('LX', 'LOGIN', 'LOGIN');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('DA', 'DATABASE AUDIT SPECIFICATION', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('DN', 'EVENT NOTIFICATION DATABASE', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('DT', 'TRIGGER DATABASE', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('MK', 'MASTER KEY', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('DK', 'DATABASE ENCRYPTION KEY', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('ON', 'EVENT NOTIFICATION OBJECT', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('PF', 'PARTITION FUNCTION', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('PR', 'BROKER PRIORITY', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('PS', 'PARTITION SCHEME', 'DATABASE');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AQ', 'ADHOC QUERY', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AF', 'AGGREGATE', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AP', 'Undocumented', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('C ', 'CHECK CONSTRAINT', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('D ', 'DEFAULT', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('EN', 'EVENT NOTIFICATION', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('F ', 'FOREIGN KEY CONSTRAINT', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('FS', 'FUNCTION SCALAR ASSEMBLY ', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('FT', 'FUNCTION TABLE-VALUED ASSEMBLY ', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('FN', 'FUNCTION SCALAR SQL', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('IX', 'INDEX', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('IF', 'FUNCTION TABLE-VALUED INLINE SQL', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('IS', 'FUNCTION SCALAR INLINE SQL ', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('IT', 'INTERNAL TABLE', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('PQ', 'PREPARED ADHOC QUERY', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('PK', 'PRIMARY KEY', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('P ', 'STORED PROCEDURE', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('PC', 'STORED PROCEDURE ASSEMBLY', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('RF', 'STORED PROCEDURE REPLICATION FILTER', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('R ', 'RULE', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('ST', 'STATISTICS', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SQ', 'QUEUE', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SN', 'SYNONYM', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('S ', 'TABLE SYSTEM', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('TF', 'FUNCTION TABLE-VALUED SQL', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('TA', 'TRIGGER ASSEMBLY', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('TR', 'TRIGGER', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('UQ', 'UNIQUE CONSTRAINT', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('U ', 'TABLE', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('V ', 'VIEW', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('X ', 'STORED PROCEDURE EXTENDED', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('XR', 'XREL TREE', 'OBJECT');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AU', 'ASYMMETRIC KEY USER', 'USER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('CU', 'CERTIFICATE USER', 'USER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('GU', 'GROUP USER', 'USER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SU', 'SQL USER', 'USER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('WU', 'WINDOWS USER', 'USER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('A ', 'SERVER AUDIT', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('CD', 'CREDENTIAL', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('CP', 'CRYPTOGRAPHIC PROVIDER', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('RG', 'RESOURCE GOVERNOR', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SA', 'SERVER AUDIT SPECIFICATION', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SD', 'EVENT NOTIFICATION SERVER', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SG', 'SERVER ROLE', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('T ', 'TRIGGER SERVER', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SE', 'EVENT SESSION', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('CO', 'SERVER CONFIG', 'SERVER');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('AL', 'ASYMMETRIC KEY LOGIN', 'LOGIN');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('CL', 'CERTIFICATE LOGIN', 'LOGIN');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('SL', 'SQL LOGIN', 'LOGIN');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('WG', 'WINDOWS GROUP', 'LOGIN');
INSERT INTO sys.dm_audit_class_type_map (class_type, class_type_desc, securable_class_desc) VALUES ('WL', 'WINDOWS LOGIN', 'LOGIN');