CREATE TABLE INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
(
    CONSTRAINT_CATALOG nvarchar(128),
    CONSTRAINT_SCHEMA nvarchar(128),
    CONSTRAINT_NAME sysname NOT NULL,
    DOMAIN_CATALOG nvarchar(128),
    DOMAIN_SCHEMA nvarchar(128),
    DOMAIN_NAME sysname NOT NULL,
    IS_DEFERRABLE varchar(2) NOT NULL,
    INITIALLY_DEFERRED varchar(2) NOT NULL
);