CREATE TABLE sys.dm_repl_traninfo
(
    fp2p_pub_exists tinyint,
    db_ver int,
    comp_range_address varbinary(8),
    textinfo_address varbinary(8),
    fsinfo_address varbinary(8),
    begin_lsn nvarchar(24),
    commit_lsn nvarchar(24),
    dbid smallint,
    rows int,
    xdesid nvarchar(24),
    artcache_table_address varbinary(8),
    server nvarchar(256),
    server_len_in_bytes int,
    [database] nvarchar(256),
    db_len_in_bytes int,
    originator nvarchar(256),
    originator_len_in_bytes int,
    orig_db nvarchar(256),
    orig_db_len_in_bytes int,
    cmds_in_tran int,
    is_boundedupdate_singleton tinyint,
    begin_update_lsn nvarchar(24),
    delete_lsn nvarchar(24),
    last_end_lsn nvarchar(24),
    fcomplete tinyint,
    fcompensated tinyint,
    fprocessingtext tinyint,
    max_cmds_in_tran int,
    begin_time datetime,
    commit_time datetime,
    session_id int,
    session_phase nvarchar(200),
    is_known_cdc_tran tinyint,
    error_count int
);