CREATE TABLE sys.dm_db_partition_stats
(
    partition_id bigint NOT NULL,
    object_id int NOT NULL,
    index_id int NOT NULL,
    partition_number int NOT NULL,
    in_row_data_page_count bigint NOT NULL,
    in_row_used_page_count bigint NOT NULL,
    in_row_reserved_page_count bigint NOT NULL,
    lob_used_page_count bigint NOT NULL,
    lob_reserved_page_count bigint NOT NULL,
    row_overflow_used_page_count bigint NOT NULL,
    row_overflow_reserved_page_count bigint NOT NULL,
    used_page_count bigint NOT NULL,
    reserved_page_count bigint NOT NULL,
    row_count bigint NOT NULL
);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (196608, 3, 1, 1, 8, 10, 17, 0, 0, 0, 0, 10, 17, 701);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (327680, 5, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 113);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (458752, 7, 1, 1, 2, 4, 4, 0, 0, 0, 0, 4, 4, 127);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949953880064, 7, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 127);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (524288, 8, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 2);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474977824768, 17, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949954535424, 17, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424931246080, 17, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474977955840, 19, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 2);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474978217984, 23, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474978283520, 24, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 2);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474978349056, 25, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474978480128, 27, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 15);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949955190784, 27, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 15);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424931901440, 27, 3, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 15);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474978611200, 29, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 145);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474978938880, 34, 1, 1, 3, 5, 5, 0, 0, 0, 0, 5, 5, 124);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949955649536, 34, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 124);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424932360192, 34, 3, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 124);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (1125899909070848, 34, 4, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 124);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474979397632, 41, 1, 1, 10, 12, 17, 0, 0, 0, 0, 12, 17, 567);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949956108288, 41, 2, 1, 5, 7, 7, 0, 0, 0, 0, 7, 7, 567);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474979594240, 44, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949956304896, 44, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474979725312, 46, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949956435968, 46, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424933146624, 46, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (1125899909857280, 46, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474979921920, 49, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 9);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474979987456, 50, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 34);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949956698112, 50, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 34);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424933408768, 50, 3, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 34);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980052992, 51, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949956763648, 51, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980249600, 54, 1, 1, 7, 9, 9, 0, 0, 0, 0, 9, 9, 279);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949956960256, 54, 2, 1, 2, 4, 4, 0, 0, 0, 0, 4, 4, 279);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980315136, 55, 1, 1, 2, 4, 4, 0, 0, 0, 0, 4, 4, 439);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949957025792, 55, 2, 1, 2, 4, 4, 0, 0, 0, 0, 4, 4, 439);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980511744, 58, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 23);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949957222400, 58, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 23);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980577280, 59, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980642816, 60, 1, 1, 37, 39, 41, 4, 4, 0, 0, 43, 45, 289);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980904960, 64, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 16);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949957615616, 64, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 16);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474980970496, 65, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981101568, 67, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949957812224, 67, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424934522880, 67, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981167104, 68, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981232640, 69, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949957943296, 69, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424934653952, 69, 3, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981363712, 71, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981429248, 72, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981494784, 73, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981560320, 74, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 215);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949958270976, 74, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 215);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981625856, 75, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 132);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949958336512, 75, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 132);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474981822464, 78, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949958533120, 78, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982084608, 82, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982281216, 85, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982608896, 90, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 97);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949959319552, 90, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 97);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982674432, 91, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 99);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949959385088, 91, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 99);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982739968, 92, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 112);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982805504, 93, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 18);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949959516160, 93, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 18);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982871040, 94, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474982936576, 95, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949959647232, 95, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424936357888, 95, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474983002112, 96, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949959712768, 96, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (844424936423424, 96, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474983067648, 97, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 3);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949959778304, 97, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 3);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (281474983133184, 98, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 8);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (562949959843840, 98, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 8);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038910976, 21575115, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 3);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038976512, 53575229, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 7);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039042048, 85575343, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 17);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039107584, 117575457, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 18);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039173120, 149575571, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 3);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039238656, 181575685, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 15);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039304192, 213575799, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 3);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039369728, 245575913, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 51);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039435264, 277576027, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 44);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039500800, 309576141, 1, 1, 3, 5, 5, 0, 0, 0, 0, 5, 5, 36);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039566336, 341576255, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039631872, 373576369, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 40);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039697408, 405576483, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 45);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039762944, 437576597, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 57);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039828480, 469576711, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 14);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039894016, 501576825, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 7);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594039959552, 533576939, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594040025088, 565577053, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 5);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594040090624, 933578364, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594040156160, 933578364, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038583296, 1993058136, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594037993472, 1993058136, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038648832, 2025058250, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038124544, 2025058250, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038714368, 2057058364, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038255616, 2057058364, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038321152, 2073058421, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038386688, 2073058421, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038452224, 2089058478, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038517760, 2089058478, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038779904, 2105058535, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 40);
INSERT INTO sys.dm_db_partition_stats (partition_id, object_id, index_id, partition_number, in_row_data_page_count, in_row_used_page_count, in_row_reserved_page_count, lob_used_page_count, lob_reserved_page_count, row_overflow_used_page_count, row_overflow_reserved_page_count, used_page_count, reserved_page_count, row_count) VALUES (72057594038845440, 2137058649, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 3);