CREATE TABLE sys.conversation_endpoints
(
    conversation_handle uniqueidentifier NOT NULL,
    conversation_id uniqueidentifier NOT NULL,
    is_initiator bit NOT NULL,
    service_contract_id int NOT NULL,
    conversation_group_id uniqueidentifier NOT NULL,
    service_id int NOT NULL,
    lifetime datetime NOT NULL,
    state char(2) NOT NULL,
    state_desc nvarchar(60),
    far_service nvarchar(256) NOT NULL,
    far_broker_instance nvarchar(128),
    principal_id int NOT NULL,
    far_principal_id int NOT NULL,
    outbound_session_key_identifier uniqueidentifier NOT NULL,
    inbound_session_key_identifier uniqueidentifier NOT NULL,
    security_timestamp datetime NOT NULL,
    dialog_timer datetime NOT NULL,
    send_sequence bigint NOT NULL,
    last_send_tran_id binary(6) NOT NULL,
    end_dialog_sequence bigint NOT NULL,
    receive_sequence bigint NOT NULL,
    receive_sequence_frag int NOT NULL,
    system_sequence bigint NOT NULL,
    first_out_of_order_sequence bigint NOT NULL,
    last_out_of_order_sequence bigint NOT NULL,
    last_out_of_order_frag int NOT NULL,
    is_system bit NOT NULL,
    priority tinyint NOT NULL
);