CREATE TABLE sys.types
(
    name sysname NOT NULL,
    system_type_id tinyint NOT NULL,
    user_type_id int NOT NULL,
    schema_id int NOT NULL,
    principal_id int,
    max_length smallint NOT NULL,
    precision tinyint NOT NULL,
    scale tinyint NOT NULL,
    collation_name sysname,
    is_nullable bit,
    is_user_defined bit NOT NULL,
    is_assembly_type bit NOT NULL,
    default_object_id int NOT NULL,
    rule_object_id int NOT NULL,
    is_table_type bit NOT NULL
);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('image', 34, 34, 4, null, 16, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('text', 35, 35, 4, null, 16, 0, 0, 'French_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('uniqueidentifier', 36, 36, 4, null, 16, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('date', 40, 40, 4, null, 3, 10, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('time', 41, 41, 4, null, 5, 16, 7, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('datetime2', 42, 42, 4, null, 8, 27, 7, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('datetimeoffset', 43, 43, 4, null, 10, 34, 7, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('tinyint', 48, 48, 4, null, 1, 3, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('smallint', 52, 52, 4, null, 2, 5, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('int', 56, 56, 4, null, 4, 10, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('smalldatetime', 58, 58, 4, null, 4, 16, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('real', 59, 59, 4, null, 4, 24, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('money', 60, 60, 4, null, 8, 19, 4, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('datetime', 61, 61, 4, null, 8, 23, 3, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('float', 62, 62, 4, null, 8, 53, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('sql_variant', 98, 98, 4, null, 8016, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('ntext', 99, 99, 4, null, 16, 0, 0, 'French_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('bit', 104, 104, 4, null, 1, 1, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('decimal', 106, 106, 4, null, 17, 38, 38, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('numeric', 108, 108, 4, null, 17, 38, 38, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('smallmoney', 122, 122, 4, null, 4, 10, 4, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('bigint', 127, 127, 4, null, 8, 19, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('hierarchyid', 240, 128, 4, null, 892, 0, 0, null, 1, 0, 1, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('geometry', 240, 129, 4, null, -1, 0, 0, null, 1, 0, 1, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('geography', 240, 130, 4, null, -1, 0, 0, null, 1, 0, 1, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('varbinary', 165, 165, 4, null, 8000, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('varchar', 167, 167, 4, null, 8000, 0, 0, 'French_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('binary', 173, 173, 4, null, 8000, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('char', 175, 175, 4, null, 8000, 0, 0, 'French_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('timestamp', 189, 189, 4, null, 8, 0, 0, null, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('nvarchar', 231, 231, 4, null, 8000, 0, 0, 'French_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('nchar', 239, 239, 4, null, 8000, 0, 0, 'French_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('xml', 241, 241, 4, null, -1, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES ('sysname', 231, 256, 4, null, 256, 0, 0, 'French_CI_AS', 0, 0, 0, 0, 0, 0);