CREATE TABLE sys.sysservers
(
    srvid smallint,
    srvstatus smallint,
    srvname sysname NOT NULL,
    srvproduct sysname NOT NULL,
    providername nvarchar(128) NOT NULL,
    datasource nvarchar(4000),
    location nvarchar(4000),
    providerstring nvarchar(4000),
    schemadate datetime NOT NULL,
    topologyx int,
    topologyy int,
    catalog sysname,
    srvcollation sysname,
    connecttimeout int,
    querytimeout int,
    srvnetname char(30),
    isremote bit,
    rpc bit NOT NULL,
    pub bit NOT NULL,
    sub bit,
    dist bit,
    dpub bit,
    rpcout bit NOT NULL,
    dataaccess bit NOT NULL,
    collationcompatible bit NOT NULL,
    system bit NOT NULL,
    useremotecollation bit NOT NULL,
    lazyschemavalidation bit NOT NULL,
    collation sysname,
    nonsqlsub bit
);
INSERT INTO sys.sysservers (srvid, srvstatus, srvname, srvproduct, providername, datasource, location, providerstring, schemadate, topologyx, topologyy, catalog, srvcollation, connecttimeout, querytimeout, srvnetname, isremote, rpc, pub, sub, dist, dpub, rpcout, dataaccess, collationcompatible, system, useremotecollation, lazyschemavalidation, collation, nonsqlsub) VALUES (0, 1089, 'SV-SQLINFO\SQLINFO', 'SQL Server', 'SQLOLEDB', 'SV-SQLINFO\SQLINFO', null, null, '2011-08-19 08:54:05.900', 0, 0, null, null, 0, 0, 'SV-SQLINFO\SQLINFO            ', 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, null, 0);