CREATE TABLE sys.xml_schema_types
(
    xml_component_id int NOT NULL,
    xml_collection_id int NOT NULL,
    xml_namespace_id int NOT NULL,
    is_qualified bit NOT NULL,
    name nvarchar(4000),
    symbol_space char(1) NOT NULL,
    symbol_space_desc nvarchar(60),
    kind char(1) NOT NULL,
    kind_desc nvarchar(60),
    derivation char(1) NOT NULL,
    derivation_desc nvarchar(60),
    base_xml_component_id int,
    scoping_xml_component_id int,
    is_abstract bit NOT NULL,
    allows_mixed_content bit NOT NULL,
    is_extension_blocked bit NOT NULL,
    is_restriction_blocked bit NOT NULL,
    is_final_extension bit NOT NULL,
    is_final_restriction bit NOT NULL,
    is_final_list_member bit NOT NULL,
    is_final_union_member bit NOT NULL
);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (6, 1, 1, 1, 'anyType', 'T', 'TYPE', 'N', 'ANY_TYPE', 'N', 'NONE', null, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (11, 1, 1, 1, 'anySimpleType', 'T', 'TYPE', 'Z', 'ANY_SIMPLE_TYPE', 'R', 'RESTRICTION', 6, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (15, 1, 1, 1, 'string', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (16, 1, 1, 1, 'boolean', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (17, 1, 1, 1, 'float', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (18, 1, 1, 1, 'double', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (19, 1, 1, 1, 'decimal', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (20, 1, 1, 1, 'duration', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (21, 1, 1, 1, 'dateTime', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (22, 1, 1, 1, 'time', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (23, 1, 1, 1, 'date', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (24, 1, 1, 1, 'gYearMonth', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (25, 1, 1, 1, 'gYear', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (26, 1, 1, 1, 'gMonthDay', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (27, 1, 1, 1, 'gDay', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (28, 1, 1, 1, 'gMonth', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (29, 1, 1, 1, 'hexBinary', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (30, 1, 1, 1, 'base64Binary', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (31, 1, 1, 1, 'anyURI', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (32, 1, 1, 1, 'QName', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (33, 1, 1, 1, 'NOTATION', 'T', 'TYPE', 'P', 'PRIMITIVE_TYPE', 'R', 'RESTRICTION', 11, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (100, 1, 1, 1, 'normalizedString', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (101, 1, 1, 1, 'token', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 100, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (102, 1, 1, 1, 'language', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 101, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (103, 1, 1, 1, 'Name', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 101, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (104, 1, 1, 1, 'NCName', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 103, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (105, 1, 1, 1, 'ID', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 104, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (106, 1, 1, 1, 'IDREF', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 104, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (107, 1, 1, 1, 'ENTITY', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 104, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (108, 1, 1, 1, 'NMTOKEN', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 101, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (109, 1, 1, 1, 'integer', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (110, 1, 1, 1, 'nonPositiveInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 109, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (111, 1, 1, 1, 'negativeInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 110, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (112, 1, 1, 1, 'long', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 109, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (113, 1, 1, 1, 'int', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 112, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (114, 1, 1, 1, 'short', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 113, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (115, 1, 1, 1, 'byte', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 114, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (116, 1, 1, 1, 'nonNegativeInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 109, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (117, 1, 1, 1, 'unsignedLong', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 116, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (118, 1, 1, 1, 'unsignedInt', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 117, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (119, 1, 1, 1, 'unsignedShort', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 118, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (120, 1, 1, 1, 'unsignedByte', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 119, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (121, 1, 1, 1, 'positiveInteger', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 116, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (200, 1, 1, 1, 'IDREFS', 'T', 'TYPE', 'L', 'LIST_TYPE', 'R', 'RESTRICTION', 106, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (201, 1, 1, 1, 'ENTITIES', 'T', 'TYPE', 'L', 'LIST_TYPE', 'R', 'RESTRICTION', 107, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (202, 1, 1, 1, 'NMTOKENS', 'T', 'TYPE', 'L', 'LIST_TYPE', 'R', 'RESTRICTION', 108, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (263, 1, 3, 1, 'xmlSpaceEnum', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (300, 1, 2, 1, 'sqlDbTypeEnum', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (301, 1, 2, 1, 'sqlCompareOptionsEnum', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (302, 1, 2, 1, 'sqlCompareOptionsList', 'T', 'TYPE', 'L', 'LIST_TYPE', 'N', 'NONE', null, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (303, 1, 2, 1, 'char', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (304, 1, 2, 1, 'nchar', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (305, 1, 2, 1, 'varchar', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (306, 1, 2, 1, 'nvarchar', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (307, 1, 2, 1, 'text', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (308, 1, 2, 1, 'ntext', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (309, 1, 2, 1, 'varbinary', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (310, 1, 2, 1, 'binary', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (311, 1, 2, 1, 'image', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (312, 1, 2, 1, 'timestamp', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 30, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (313, 1, 2, 1, 'timestampNumeric', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 112, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (314, 1, 2, 1, 'decimal', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (315, 1, 2, 1, 'numeric', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (316, 1, 2, 1, 'bigint', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 112, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (317, 1, 2, 1, 'int', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 113, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (318, 1, 2, 1, 'smallint', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 114, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (319, 1, 2, 1, 'tinyint', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 120, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (320, 1, 2, 1, 'bit', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 16, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (321, 1, 2, 1, 'float', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 18, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (322, 1, 2, 1, 'real', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 17, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (324, 1, 2, 1, 'datetime', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (325, 1, 2, 1, 'smalldatetime', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (326, 1, 2, 1, 'money', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (327, 1, 2, 1, 'smallmoney', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 19, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (328, 1, 2, 1, 'uniqueidentifier', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (329, 1, 2, 1, 'xml', 'T', 'TYPE', 'K', 'COMPLEX_TYPE', 'R', 'RESTRICTION', 6, null, 0, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (330, 1, 2, 1, 'date', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 23, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (331, 1, 2, 1, 'time', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 22, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (332, 1, 2, 1, 'datetime2', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (333, 1, 2, 1, 'datetimeoffset', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 21, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (334, 1, 2, 1, 'hierarchyid', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 15, null, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.xml_schema_types (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_abstract, allows_mixed_content, is_extension_blocked, is_restriction_blocked, is_final_extension, is_final_restriction, is_final_list_member, is_final_union_member) VALUES (360, 1, 2, 1, 'dbobject', 'T', 'TYPE', 'S', 'SIMPLE_TYPE', 'R', 'RESTRICTION', 31, null, 0, 0, 0, 0, 0, 0, 0, 0);