CREATE TABLE sys.computed_columns
(
    object_id int NOT NULL,
    name sysname,
    column_id int NOT NULL,
    system_type_id tinyint NOT NULL,
    user_type_id int NOT NULL,
    max_length smallint NOT NULL,
    precision tinyint NOT NULL,
    scale tinyint NOT NULL,
    collation_name sysname,
    is_nullable bit,
    is_ansi_padded bit NOT NULL,
    is_rowguidcol bit NOT NULL,
    is_identity bit NOT NULL,
    is_filestream bit NOT NULL,
    is_replicated bit,
    is_non_sql_subscribed bit,
    is_merge_published bit,
    is_dts_replicated bit,
    is_xml_document bit NOT NULL,
    xml_collection_id int NOT NULL,
    default_object_id int NOT NULL,
    rule_object_id int NOT NULL,
    definition nvarchar(max),
    uses_database_collation bit NOT NULL,
    is_persisted bit NOT NULL,
    is_computed bit NOT NULL,
    is_sparse bit NOT NULL,
    is_column_set bit NOT NULL
);