CREATE TABLE INFORMATION_SCHEMA.SCHEMATA
(
    CATALOG_NAME nvarchar(128),
    SCHEMA_NAME sysname NOT NULL,
    SCHEMA_OWNER nvarchar(128),
    DEFAULT_CHARACTER_SET_CATALOG sysname,
    DEFAULT_CHARACTER_SET_SCHEMA sysname,
    DEFAULT_CHARACTER_SET_NAME sysname
);
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'dbo', 'dbo', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'guest', 'guest', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'INFORMATION_SCHEMA', 'INFORMATION_SCHEMA', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'sys', 'sys', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_owner', 'db_owner', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_accessadmin', 'db_accessadmin', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_securityadmin', 'db_securityadmin', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_ddladmin', 'db_ddladmin', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_backupoperator', 'db_backupoperator', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_datareader', 'db_datareader', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_datawriter', 'db_datawriter', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_denydatareader', 'db_denydatareader', null, null, 'iso_1');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES ('BD5W6_424P', 'db_denydatawriter', 'db_denydatawriter', null, null, 'iso_1');